"""PyTorch workflow orchestration facade — parity with ptycho/workflows/components.py.

Spec-pinned re-exporting facade. The implementation slabs behind it were split
by responsibility into sibling submodules (``bundle_io``, ``containers``,
``dataloaders``, ``rect_s1s2``, ``lightning_service``, ``legacy``); every name
below is re-exported unchanged so ``from ptycho_torch.workflows.components import ...``
and monkeypatch targets resolve exactly as before the split.
"""
from .bundle_io import (
    _BUNDLE_SCALING_METADATA,
    _BUNDLE_AMPLITUDE_PHYSICS_GAIN_RECORD,
    _persist_bundle_scaling_metadata,
    _read_bundle_scaling_metadata,
    _read_bundle_amplitude_physics_gain_record,
    _decode_bundle_metadata,
    _strictly_reconstruct_bundle_model,
    _reconstruct_inference_bundle_explicit,
    _pinned_bundle_snapshot,
    _decode_pinned_inference_bundle,
    load_inference_bundle_torch,
)

from .containers import (
    _canonicalize_ci_probe_modes,
    _get_finalized_ci_statistics,
    _resolve_nphotons,
    _attach_physics_scale,
    _get_container_tensor_required,
    attach_container_ci_fields,
    _adapt_container_for_ci,
    _ensure_container,
)

from .dataloaders import (
    _resolve_torch_training_seed,
    _build_lightning_dataloaders,
    _build_inference_dataloader,
)

from .rect_s1s2 import (
    _RECT_S1S2_IDENTITY_FIELD,
    _move_batch_to_device,
    _RectS1S2IndexedRows,
    _RectS1S2SelectedBatch,
    _rect_s1s2_attach_identities,
    _rect_s1s2_verify_collated_identities,
    _RectS1S2SelectedDataset,
    _RectS1S2MaintainedCollation,
    _rect_s1s2_indexable_dataset,
    _rebuild_rect_s1s2_loader,
    _rect_s1s2_batch_axes,
    _inspect_rect_s1s2_channels,
    _initialize_rect_s1s2_unmanaged,
    _initialize_rect_s1s2,
    _write_training_summary_atomic,
    _publish_training_summary_and_barrier,
    _rect_s1s2_training_loader,
    _effective_dataloader_settings,
)

from .lightning_service import (
    _CHECKPOINT_SELECTION_SCHEMA,
    _checkpoint_artifact_path,
    _checkpoint_file_sha256,
    _checkpoint_score_value,
    _in_memory_checkpoint_selection,
    _write_checkpoint_selection_atomic,
    _read_checkpoint_selection,
    _publish_checkpoint_selection_and_barrier,
    _rank_shared_checkpoint_selection_token,
    _FinalModelSelectionCallback,
    _MilestoneCheckpointCallback,
    _LossHistoryCallback,
    _TrainingSummaryCallback,
    _ServingModelCheckpointMixin,
    _ServingModelCheckpoint,
    _resolve_checkpoint_monitor,
    _validate_training_execution_input,
    _train_with_lightning,
)

from .legacy import (
    run_cdi_example_torch,
    _reassemble_cdi_image_torch_mmap,
    _reassemble_cdi_image_torch,
    _reassemble_position_with_legacy_geometry,
    train_cdi_model_torch,
)

__all__ = [
    '_BUNDLE_AMPLITUDE_PHYSICS_GAIN_RECORD',
    '_BUNDLE_SCALING_METADATA',
    '_CHECKPOINT_SELECTION_SCHEMA',
    '_FinalModelSelectionCallback',
    '_LossHistoryCallback',
    '_MilestoneCheckpointCallback',
    '_RECT_S1S2_IDENTITY_FIELD',
    '_RectS1S2IndexedRows',
    '_RectS1S2MaintainedCollation',
    '_RectS1S2SelectedBatch',
    '_RectS1S2SelectedDataset',
    '_ServingModelCheckpoint',
    '_ServingModelCheckpointMixin',
    '_TrainingSummaryCallback',
    '_adapt_container_for_ci',
    '_attach_physics_scale',
    '_build_inference_dataloader',
    '_build_lightning_dataloaders',
    '_canonicalize_ci_probe_modes',
    '_checkpoint_artifact_path',
    '_checkpoint_file_sha256',
    '_checkpoint_score_value',
    '_decode_bundle_metadata',
    '_decode_pinned_inference_bundle',
    '_effective_dataloader_settings',
    '_ensure_container',
    '_get_container_tensor_required',
    '_get_finalized_ci_statistics',
    '_in_memory_checkpoint_selection',
    '_initialize_rect_s1s2',
    '_initialize_rect_s1s2_unmanaged',
    '_inspect_rect_s1s2_channels',
    '_move_batch_to_device',
    '_persist_bundle_scaling_metadata',
    '_pinned_bundle_snapshot',
    '_publish_checkpoint_selection_and_barrier',
    '_publish_training_summary_and_barrier',
    '_rank_shared_checkpoint_selection_token',
    '_read_bundle_amplitude_physics_gain_record',
    '_read_bundle_scaling_metadata',
    '_read_checkpoint_selection',
    '_reassemble_cdi_image_torch',
    '_reassemble_cdi_image_torch_mmap',
    '_reassemble_position_with_legacy_geometry',
    '_rebuild_rect_s1s2_loader',
    '_reconstruct_inference_bundle_explicit',
    '_rect_s1s2_attach_identities',
    '_rect_s1s2_batch_axes',
    '_rect_s1s2_indexable_dataset',
    '_rect_s1s2_training_loader',
    '_rect_s1s2_verify_collated_identities',
    '_resolve_checkpoint_monitor',
    '_resolve_nphotons',
    '_resolve_torch_training_seed',
    '_strictly_reconstruct_bundle_model',
    '_train_with_lightning',
    '_validate_training_execution_input',
    '_write_checkpoint_selection_atomic',
    '_write_training_summary_atomic',
    'attach_container_ci_fields',
    'load_inference_bundle_torch',
    'run_cdi_example_torch',
    'train_cdi_model_torch',
]
