#!/bin/bash
# Migration from Legacy Syntax Example
# Shows how to convert old commands to the current centered-nearest contract

echo "=================================================="
echo "Migration from Legacy to Centered-Nearest Grouping"
echo "=================================================="

echo ""
echo "SCENARIO 1: Simple gridsize=1 training"
echo "----------------------------------------"
echo "OLD (legacy) command:"
echo "  ptycho_train --train_data_file data.npz --n_images 1000 --output_dir old_run"
echo ""
echo "NEW (canonical) command:"
echo "  ptycho_train --train_data_file data.npz --training_groups 1000 --output_dir new_run"
echo ""
echo "NEW (with explicit candidate pool):"
echo "  ptycho_train --train_data_file data.npz --train_raw_selection 1000 --training_groups 1000 --output_dir new_run"
echo "  # 1000 candidate rows, 1000 groups (every row a center)"
echo ""

echo "SCENARIO 2: Gridsize>1 training"
echo "----------------------------------------"
echo "OLD command (n_images means groups):"
echo "  ptycho_train --train_data_file data.npz --n_images 100 --gridsize 2 --output_dir old_run"
echo "  # 100 groups of 4 rows (1 center + 3 nearest non-center candidates)"
echo ""
echo "NEW (canonical):"
echo "  ptycho_train --train_data_file data.npz --training_groups 100 --gridsize 2 --output_dir new_run"
echo ""
echo "NEW (with explicit candidate pool - recommended):"
echo "  ptycho_train --train_data_file data.npz --train_raw_selection 400 --training_groups 100 --gridsize 2 --output_dir new_run"
echo "  # Clear: load 400 candidate rows, create 100 groups (100 unique centers)"
echo ""

echo "SCENARIO 3: Memory-limited training"
echo "----------------------------------------"
echo "OLD approach (confusing):"
echo "  # Want to load 2000 rows but only use 500 as centers with gridsize=2"
echo ""
echo "NEW approach (clear):"
echo "  ptycho_train --train_data_file data.npz --train_raw_selection 2000 --training_groups 500 --gridsize 2 --output_dir new_run"
echo "  # Clear: load 2000 candidate rows, create 500 groups (500 unique centers)"
echo ""

echo "SCENARIO 4: Inference"
echo "----------------------------------------"
echo "OLD inference command:"
echo "  ptycho_inference --model_path model/ --test_data data.npz --n_images 1000"
echo ""
echo "NEW inference (canonical):"
echo "  ptycho_inference --model_path model/ --test_data data.npz --inference_groups 1000"
echo ""
echo "NEW inference (with candidate-pool control):"
echo "  ptycho_inference --model_path model/ --test_data data.npz --inference_raw_selection 5000 --inference_groups 1000"
echo "  # Load 5000 candidate rows, process 1000 groups (1000 bounded centers)"
echo ""

echo "SCENARIO 5: Comparison scripts"
echo "----------------------------------------"
echo "OLD comparison:"
echo "  python scripts/compare_models.py --pinn_dir pinn/ --baseline_dir base/ --test_data data.npz"
echo ""
echo "NEW comparison with sampling:"
echo "  python scripts/compare_models.py --pinn_dir pinn/ --baseline_dir base/ --test_data data.npz \\"
echo "    --n-test-groups 1000 --n-test-subsample 5000 --test-subsample-seed 42"
echo ""

echo "=================================================="
echo "Migration Guidelines:"
echo "1. --n_images / --n_groups map to --training_groups (exact group count = unique centers)"
echo "2. --n_subsample maps to --train_raw_selection (candidate pool size)"
echo "3. Use --subsample_seed for reproducible selection"
echo "4. training_groups can never exceed the candidate pool size (no oversampling)"
echo "5. --enable_oversampling and --neighbor_pool_size are retired; migration diagnostics name them"
echo "=================================================="

# Practical migration example
echo ""
echo "RUNNING PRACTICAL EXAMPLE:"
echo "Comparing old vs new syntax with same result..."
echo ""

# These two commands should produce identical results:
echo "Legacy mode (if dataset exists):"
# ptycho_train --train_data_file datasets/fly/fly001_transposed.npz --n_images 100 --output_dir migration_legacy --nepochs 1

echo ""
echo "New canonical mode (if dataset exists):"
# ptycho_train --train_data_file datasets/fly/fly001_transposed.npz --training_groups 100 --train_raw_selection 100 --output_dir migration_new --nepochs 1