"""Photon-flux sweep datasets for calibrated object-scale invariance.

Goal: show that CI reconstruction remains in the object's stored absolute units
when incident-photon dose and the stored physical probe are calibrated together.

Design (single object + probe, only flux varies):
  * ONE frozen lines object (strong amplitude contrast, reuses make_lines_datasets)
    and ONE probe. Identical scan positions across all fluxes.
  * Evaluate the noiseless raw object/probe forward at several target mean-count
    levels {1, 100, 10000}. Scale the stored physical probe by the matching
    amplitude factor and draw fresh Poisson counts independently at each level.
  * Train ONCE at the mid flux (mean 100); flux_sweep_eval.py then evaluates that
    single checkpoint at all three test fluxes x inference varpro {ON, OFF}.

Prediction: the recovered object gauge remains invariant across mean-count levels.
An unchanged-probe square-root-dose drift belongs only to a separate negative
control and is not generated by this calibrated builder.

Outputs (N=64, gridsize 1) in .artifacts/varpro_ablation/datasets/:
  fluxsweep_N64_train.npz              (mean count 100)
  fluxsweep_N64_mean{1,100,10000}_test.npz
"""
import json
import sys
from pathlib import Path

import numpy as np

REPO = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO)); sys.path.insert(0, str(REPO / "scripts/studies"))

import make_synthetic_truth_datasets as M
from make_lines_datasets import frozen_lines_object

N = 64
TRAIN_MEAN = 100.0
TEST_MEANS = [1.0, 100.0, 10000.0]


def split_coords(spec, split):
    cfg = spec[split]
    return M.scan_positions(
        spec["obj_res"],
        N,
        cfg["n"],
        cfg["seed"],
        cfg["jitter"],
    )


def main() -> int:
    spec = M.SPECS[N]
    probe = M.load_probe(spec["probe_src"], N=N)
    obj = frozen_lines_object(N, spec["obj_res"])

    prov = {"task": "amendment #14 photon-flux sweep (s1/s2 scale absorption)",
            "object": "frozen lines (make_lines_datasets.frozen_lines_object)",
            "N": N, "train_mean": TRAIN_MEAN, "test_means": TEST_MEANS,
            "scale_contract_version": M.CI_SCALE_CONTRACT,
            "measurement_domain": M.COUNT_INTENSITY,
            "probe_gauge": M.PHYSICAL_CALIBRATED_PROBE_GAUGE,
            "convention": "fresh Poisson counts; physical probe calibrated per target mean",
            "outputs": {}}

    # --- train (mid flux) ---
    xc_tr, yc_tr = split_coords(spec, "train")
    generated_tr = M.generate_ci_count_dataset(
        obj,
        probe,
        xc_tr,
        yc_tr,
        N=N,
        target_mean_count=TRAIN_MEAN,
        poisson_seed=30_000 + spec["train"]["seed"],
    )
    counts_tr = generated_tr.payload["diff3d"]
    p_tr = M.DS_DIR / f"fluxsweep_N{N}_train.npz"
    np.savez(p_tr, **generated_tr.payload)
    prov["outputs"]["train"] = {"path": str(p_tr), "mean": round(float(counts_tr.mean()), 3),
                                "max": int(counts_tr.max()), "n": int(spec["train"]["n"]),
                                "probe_gauge": generated_tr.metadata["probe_gauge"],
                                "dose_amplitude_scale": generated_tr.dose_amplitude_scale}
    print(f"train mean={counts_tr.mean():.3f} max={counts_tr.max()}")

    # --- test sweep (same raw forward, independently sampled flux levels) ---
    xc_te, yc_te = split_coords(spec, "test")
    for mean in TEST_MEANS:
        generated = M.generate_ci_count_dataset(
            obj,
            probe,
            xc_te,
            yc_te,
            N=N,
            target_mean_count=mean,
            poisson_seed=31_000 + spec["test"]["seed"] + int(mean),
        )
        counts = generated.payload["diff3d"]
        dev = M.cross_pattern_deviation(counts)
        tag = int(mean)
        p = M.DS_DIR / f"fluxsweep_N{N}_mean{tag}_test.npz"
        np.savez(p, **generated.payload)
        prov["outputs"][f"test_mean{tag}"] = {
            "path": str(p), "mean": round(float(counts.mean()), 4),
            "max": int(counts.max()), "cross_pattern_deviation": round(dev, 4),
            "probe_gauge": generated.metadata["probe_gauge"],
            "dose_amplitude_scale": generated.dose_amplitude_scale}
        print(f"test mean~{mean:>8.1f}: counts mean={counts.mean():.4f} max={counts.max()} dev={dev:.3f}")

    with open(M.DS_DIR / "provenance_fluxsweep.json", "w") as fh:
        json.dump(prov, fh, indent=1)
    print("wrote", M.DS_DIR / "provenance_fluxsweep.json")
    return 0


if __name__ == "__main__":
    sys.exit(main())
