#!/usr/bin/env python3
"""Generate SIM-LINES-4X metrics table for the paper."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


METRICS = [
    ("mae", "MAE"),
    ("psnr", "PSNR (dB)"),
    ("ssim", "SSIM"),
    ("ms_ssim", "MS-SSIM"),
]


def _format_value(value: float | None) -> str:
    if value is None:
        return "N/A"
    return f"{value:.6f}"


def render_table(data: dict) -> str:
    header_cells = ["Case"]
    for _, label in METRICS:
        header_cells.append(f"{label} (Amp)")
        header_cells.append(f"{label} (Phase)")

    lines = [
        "% Generated by paper/tables/scripts/generate_sim_lines_4x_metrics.py",
        "% Source: paper/data/sim_lines_4x_metrics.json (eval_reconstruction outputs)",
        r"\begin{table}[htbp]",
        r"\centering",
        (
        r"\caption{SIM-LINES-4X reconstruction metrics on the stitched test split. "
        r"Ground truth uses the simulated object, cropped to the scanned region via "
        r"scan-coordinate alignment. Test evaluation uses a random subsample "
        r"(nsamples=1000, seed=7). Phase FRC50 is undefined because the "
        r"ground-truth phase is constant zero.}"
        ),
        r"\label{tab:sim_lines_metrics}",
        r"\begin{tabular}{@{}l" + "c" * (len(header_cells) - 1) + r"@{}}",
        r"\toprule",
        " & ".join(header_cells) + r" \\",
        r"\midrule",
    ]

    for case in data["cases"]:
        row = [case["label"]]
        metrics = case["metrics"]
        for metric_key, _ in METRICS:
            amp_val, phase_val = metrics[metric_key]
            row.append(_format_value(amp_val))
            row.append(_format_value(phase_val))
        lines.append(" & ".join(row) + r" \\")

    lines.extend([r"\bottomrule", r"\end{tabular}", r"\end{table}"])
    return "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--input",
        type=Path,
        default=Path("paper/data/sim_lines_4x_metrics.json"),
        help="Input JSON metrics file.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("paper/tables/sim_lines_4x_metrics.tex"),
        help="Output LaTeX table path.",
    )
    args = parser.parse_args()

    data = json.loads(args.input.read_text(encoding="utf-8"))
    output = render_table(data)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(output, encoding="utf-8")


if __name__ == "__main__":
    main()
