# Baseline model configuration
# This ensures the baseline model is trained with model_type='supervised'

# Model Architecture Parameters
N: 64                    # Dimension of input diffraction patterns (64x64 pixels)
gridsize: 1              # Non-grid data (set to 1)
n_filters_scale: 2       # Multiplier for number of filters in conv layers
model_type: "supervised" # CRITICAL: Set to supervised for baseline model
amp_activation: "sigmoid" # Activation function for amplitude output
object_big: true         # Reconstruct large area by stitching patches
probe_big: false         # Single probe representation
probe_mask: false        # No circular mask on probe
gaussian_smoothing_sigma: 0.0  # No smoothing

# Training Parameters
nepochs: 50              # Number of training epochs
batch_size: 16           # Samples per batch (power of 2)
n_images: 512            # Number of diffraction patterns to use
learning_rate: 0.001     # Learning rate for Adam optimizer

# Physics & Loss Parameters
nphotons: 1000000.0            # Average photons per diffraction pattern
nll_weight: 1.0          # Weight for Negative Log-Likelihood loss
mae_weight: 0.0          # Weight for Mean Absolute Error loss
probe_scale: 1.0         # Probe normalization factor
probe_trainable: true    # Allow model to learn probe function
intensity_scale_trainable: true  # Allow learning intensity scale

# Data parameters (paths provided via CLI)
# train_data_file: provided via command line
# test_data_file: provided via command line
# output_dir: provided via command line