# configs/comparison_config.yaml (MODIFIED FOR GRIDSIZE=2)
N: 64
gridsize: 2
n_filters_scale: 2
model_type: 'pinn'
amp_activation: 'sigmoid'
object_big: true
probe_big: false
probe_mask: true
pad_object: true
probe_scale: 10.0
nepochs: 50
batch_size: 16
output_dir: "comparison_outputs"
train_data_file: "dummy_train.npz"
test_data_file: "dummy_test.npz"
n_images: 512
nphotons: 1000.0
nll_weight: 1.0
mae_weight: 0.0
probe_trainable: true
intensity_scale_trainable: true
positions_provided: true